[google_service_account]
type = "service_account"
project_id = "streamlit-financas"
private_key_id = "9ccf16022f592c6cccf3b431721e04b827d29741"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeHhQrSB7IxMPw
gZKQyl3tiPyCRpGNunnmwj9vfvUMuGL05N7lnj17LmEcSKFvYQThFEd+XotpJ1+r
ofVA6raG65w/MF3smW4JiM7jF7VhvEXsHedDzArssyMQ8O8gJ3YGCyvyC23j5vWm
hr+a8Zleh2lIHKxCyM0X3kg0qikLggZ/3sl3ytvSVNif1Fu+Rt9iOlEAT3DAtkpw
T0vA63IlbJVPnE9abzLBaoSy9LIsisfJVC8VxYFbDT6b24a9nnXkbQr0epAKLtpx
sSSNDF+0he5r6dSd4mvfkVOb02CkUvypK1ct3RWg1FxqaycDfgv/pn/KZu9NOZrO
e5HrlAe3AgMBAAECggEABbNqIPKQoMaulXRoHBrq9Qs12d3Nr94ta/tmVx15z1oZ
Wa2kBB2TwOYeSTgTKsiRz12wUDP8QC/TvFGMERAFW1FeYk1BOnkaGKaBzK1IdGKN
FzzJLE5/uSLVgyEn6TEsouSMBcX3621V2Qm0GdPxJpF1fP/Pp17FcKfEIBksfqyR
QiMKvAlFSJxn6DVTqls3GpdkuzouidCeAWrx8kM1lJeayIsZYrQ2GsIHbUR0ZeY7
wK/Xm3lqnInv5XUP8kZCiykaIbL72UlxD5krK44Giv4gnA737QoV+6YMoFaJVPXv
YKMZSKRLuxI8fZyurTYiu47ut1zEtBxFK6kMqN/udQKBgQDODMcv7jiLYgSYN+K3
7t8lWNAoS+vOgf5y5+jJJikxSWsCgn6saynlU8b4u/ZGzvZ/PhzXOSs5vZs/MVF+
2mbCsuEdLQW/tqawRKJo2pMXZWKKAsBvN5j4k5nUnFW9TqCP/nRZb3XzLqBplMUr
RpuAF8ounWOhuD1ajGQI4KV1xQKBgQDEcqtshh1pYYPimjt6OD/RaohA+IudkKPR
dj9sqiBdawS6lDpB0+++ikJP23zpajroKTuUehtb+itjRmwxdEZ3B4FSsvTYtErs
y9buEAQnntvuEip4aaIlp9CuGGyWnaOnRZHfA4QebiIC6D4g44dtM8/OcNYYilEK
hHs9Yp/bSwKBgQCUBuYKbw+8QryeRnfgQAGbqQRSDsjnYMhV8HlyGLI7ME1qTimG
4K4GjHtDMnWpRQIdQ5ggnneJUcf4TAwKIAj3Et9awH+CzUtPEt/CiFRn2HRERdnN
jJme6xr2fSGzkIsVJ26a2dJY1ER11WUYw+7uxSiA+J0dD2k0Zetv3UPBKQKBgQC2
D1PBqvWdEWvJ2Yhft7ulWCbYl7/EkiTQXddf3LdL/H+QbwkisskQfFACdHbqV7Iq
MPRvoU6zykDlq4Ffv9QCQilfPEzgfQ6nMC6LyLohAf/vPlSv7a4BWepzPl18pLHj
tvz+guKx1P2eViAmGNgMo6TmPPqeGaoLpkYU2M8vywKBgEBGg5L8dC+u8ANs9a/y
qs9uTc9cWUePVTlv5rzznnFmNJlnlVrNrnky6cHsrFwnB01ayjcq11A/Rhl4UqZP
x9gyBPH2wtdjqJs62/xoUoSRRpd14mQIoDnAKDYgGn8ZX0pABfxNPXQz3JvMF58G
nLq0IsQDRuS4LaHCOB5OhUD2
-----END PRIVATE KEY-----"""
client_email = "streamlit-access@streamlit-financas.iam.gserviceaccount.com"
client_id = "101953296058703409125"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-access@streamlit-financas.iam.gserviceaccount.com"
